using BeoControl.Interfaces;

namespace BeoControl;

/// <summary>App-level slash commands (not B&amp;O device commands).</summary>
public static class AppCommands
{
    private static readonly Dictionary<string, string> CommandDescriptions = new(StringComparer.OrdinalIgnoreCase)
    {
        ["tv"] = "Select TV",
        ["radio"] = "Select Radio",
        ["cd"] = "Select CD",
        ["cd2"] = "Select CD 2",
        ["phono"] = "Select Phono",
        ["dvd"] = "Select DVD",
        ["sat"] = "Select SAT",
        ["vtape"] = "Select V.Tape",
        ["pc"] = "Select PC",
        ["doorcam"] = "Doorcam",
        ["light"] = "Set Light source ctx",
        ["a.aux"] = "Audio Aux",
        ["v.aux"] = "Video Aux",
        ["atape"] = "Select A.Tape",
        ["atape2"] = "Select A.Tape 2",
        ["text"] = "Text",
        ["spdemo"] = "Speaker Demo",
        ["0"] = "Digit 0",
        ["1"] = "Digit 1",
        ["2"] = "Digit 2",
        ["3"] = "Digit 3",
        ["4"] = "Digit 4",
        ["5"] = "Digit 5",
        ["6"] = "Digit 6",
        ["7"] = "Digit 7",
        ["8"] = "Digit 8",
        ["9"] = "Digit 9",
        ["vol+"] = "Volume Up",
        ["vol-"] = "Volume Down",
        ["mute"] = "Mute",
        ["loudness"] = "Loudness",
        ["standby"] = "Standby",
        ["off"] = "Standby (alias)",
        ["allstandby"] = "All devices standby",
        ["alloff"] = "All devices standby (alias)",
        ["go"] = "Play / Go",
        ["play"] = "Play (alias for go)",
        ["stop"] = "Stop",
        ["record"] = "Record",
        ["up"] = "Cursor Up",
        ["down"] = "Cursor Down",
        ["left"] = "Cursor Left",
        ["right"] = "Cursor Right",
        ["menu"] = "Menu",
        ["exit"] = "Exit menu",
        ["return"] = "Return",
        ["select"] = "Select",
        ["list"] = "List",
        ["index"] = "Index",
        ["bass"] = "Bass",
        ["treble"] = "Treble",
        ["balance"] = "Balance",
        ["speaker"] = "Speaker",
        ["red"] = "Red key",
        ["green"] = "Green key",
        ["blue"] = "Blue key",
        ["yellow"] = "Yellow key",
        ["store"] = "Store",
        ["clear"] = "Clear",
        ["tune"] = "Tune",
        ["clock"] = "Clock",
        ["format"] = "Format",
        ["picture"] = "Picture",
        ["turn"] = "Turn / Mono",
        ["av"] = "AV",
        ["dvd2"] = "DVD 2",
        ["on"] = "Masterlink on",
        ["bass+"] = "Bass up",
        ["bass-"] = "Bass down",
        ["treble+"] = "Treble up",
        ["treble-"] = "Treble down",
        ["balance+"] = "Balance right",
        ["balance-"] = "Balance left",
        ["/help"] = "Show all commands",
        ["/clear"] = "Clear the log",
        ["/debug"] = "Toggle debug log messages",
        ["/exit"] = "Exit the application",
        ["/port"] = "Connect via serial/USB",
        ["/port scan"] = "Scan and list serial devices",
        ["/bt"] = "Connect via Bluetooth (BLE)",
        ["/bt scan"] = "Scan and list BLE devices",
        ["/bt-last"] = "Reconnect last BLE device",
        ["/pc2"] = "Connect to PC2 USB device",
    };

    private static readonly Dictionary<string, string> DeviceParamHints = new(StringComparer.OrdinalIgnoreCase)
    {
        [ "tv" ] = "[n]",
        [ "radio" ] = "[n]",
        [ "cd" ] = "[n]",
        [ "phono" ] = "[n]",
        [ "dvd" ] = "[n]",
        [ "sat" ] = "[n]",
        [ "pc" ] = "[n]",
        [ "light" ] = "[stop]",
        [ "atape" ] = "[n]",
        [ "atape2" ] = "[n]",
        [ "bass+" ] = "[steps]",
        [ "bass-" ] = "[steps]",
        [ "treble+" ] = "[steps]",
        [ "treble-" ] = "[steps]",
        [ "balance+" ] = "[steps]",
        [ "balance-" ] = "[steps]",
        [ "/port" ] = "[COMx] | scan]",
        [ "/bt" ] = "[scan]",
    };

    public static readonly BeoCommand[] SlashCommands =
    [
        BeoCommands.Get(CommandId.AppHelp),
        BeoCommands.Get(CommandId.AppClear),
        BeoCommands.Get(CommandId.AppDebug),
        BeoCommands.Get(CommandId.AppExit),
        BeoCommands.Get(CommandId.AppPort),
        BeoCommands.Get(CommandId.AppPortScan),
        BeoCommands.Get(CommandId.AppBt),
        BeoCommands.Get(CommandId.AppBtScan),
        BeoCommands.Get(CommandId.AppBtLast),
        BeoCommands.Get(CommandId.AppPc2),
    ];

    public static string ParamHintFor(BeoCommand command) =>
        command.ParamHint
        ?? (DeviceParamHints.TryGetValue(command.Cmd, out var hint) ? hint : string.Empty);

    public static string DescriptionFor(BeoCommand command) =>
        CommandDescriptions.TryGetValue(command.Cmd, out var description) ? description : string.Empty;
}
